In [1]:
import numpy as np

In [29]:
data = np.load("heterogeneous/Regret_final_gamma_p=1.0_ER.npz")
lst = data.files

for item in lst:
    print(item)
    print(data[item])

arr_0
[[4371.13421053 4211.95263158 4413.74210526]
 [4039.83947368 4120.60263158 4159.42105263]
 [3986.28947368 4164.82105263 4069.42105263]
 [3995.47894737 3977.57368421 3758.51842105]
 [3621.74210526 3836.27368421 4499.83421053]
 [4054.92631579 3869.66842105 4198.85526316]]
arr_1
[[ 63.35526316  13.26315789 103.54736842]
 [ 98.97631579 132.89210526  71.66842105]
 [  5.11578947  28.89473684  41.96842105]
 [102.88421053  11.36842105  44.88157895]
 [ 15.53684211  45.56842105  54.97105263]
 [112.92631579  53.95263158  81.92368421]]


In [31]:
data = np.load("heterogeneous/Regret_final_gamma_p=1.0_ER.npz")
lst = data.files

for item in lst:
    print(item)
    print(data[item])

arr_0
[[3908.67631579 3859.17631579 3941.81052632 3867.25263158 3877.67368421
  3897.18947368]
 [4246.69736842 4240.94210526 4054.09736842 3849.34736842 4167.11842105
  3722.54210526]
 [3749.54210526 3855.10263158 4166.69210526 4151.25       4129.67368421
  3591.21315789]
 [3878.64473684 3912.72631579 4141.63421053 3813.13421053 3858.22894737
  3910.26315789]
 [3673.63421053 4325.80263158 4253.28157895 3976.31842105 4223.51052632
  4116.00789474]
 [3973.80789474 4267.27894737 4095.56842105 4450.40526316 4132.13684211
  4162.95      ]]
arr_1
[[ 18.87631579  12.71842105  15.3         27.          41.44736842
  106.2       ]
 [  8.02894737  11.55789474  25.60263158  43.67368421  15.32368421
   46.65789474]
 [ 72.9         81.16578947 140.61315789  29.96052632  31.5
   70.55526316]
 [144.16578947  62.85789474  32.13947368  74.29736842  81.73421053
   25.24736842]
 [ 35.21842105  75.76578947  38.72368421  38.01315789   0.9
   13.57105263]
 [ 42.56052632  76.45263158  11.17894737 114.7263157

In [25]:
data = np.load("heterogeneous/Communication_final_gamma_p=1.0_ER.npz")
lst = data.files

for item in lst:
    print(item)
    print(data[item])

arr_0
[[250000. 250000. 250000.]
 [250000. 250000. 250000.]
 [100000. 100000. 100000.]
 [250000. 250000. 250000.]
 [250000. 250000. 250000.]
 [250000. 250000. 250000.]]
arr_1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
A = [(3082.1684210526664, 250000), (3109.6894736842464, 250000), (3153.8368421052887, 250000), (3070.5631578947646, 250000), (3120.7736842105483, 250000), (2967.7736842105564, 250000), (2991.2684210526522, 250000), (3083.5894736842447, 250000), (2942.384210526337, 250000), (2972.8894736842267, 250000), (3012.2526315789787, 250000), (2858.257894736876, 250000), (3135.6947368421165, 250000), (3180.5526315789716, 250000), (2883.268421052655, 250000), (3039.678947368444, 250000), (3249.8052631579176, 250000), (3117.3157894737024, 250000), (3143.415789473717, 250000), (3191.684210526353, 250000), (2952.757894736877, 250000), (3104.1000000000295, 250000), (3018.363157894776, 250000), (3024.6157894737044, 250000), (3068.621052631611, 250000), (3133.278947368446, 250000), (3155.4473684210875, 250000), (3130.9578947368736, 250000), (3073.736842105311, 250000), (2775.4105263157962, 250000), (3096.0473684210624, 250000), (2813.1631578947677, 250000), (2980.942105263179, 250000), (3024.331578947394, 250000), (3052.2789473684593, 250000), (3089.0368421052776, 250000), (3159.9473684210834, 250000), (2993.542105263167, 250000), (3105.189473684246, 250000), (3116.036842105296, 250000), (3088.4210526315806, 250000), (3175.3894736842635, 250000), (3309.631578947378, 250000), (3117.600000000033, 250000), (2923.0578947368567, 250000), (3105.0000000000286, 250000), (3077.526315789493, 250000), (2884.0263157894938, 250000), (3114.1894736842482, 250000), (3152.3684210526453, 250000), (3123.994736842135, 250000), (3050.857894736878, 250000), (3006.284210526351, 250000), (3065.44736842109, 250000), (3361.9263157894857, 250000), (2859.442105263181, 250000), (3022.0578947368754, 250000), (2949.8210526315993, 250000), (3229.15263157898, 250000), (3087.331578947382, 250000), (3014.9052631579116, 100000), (2986.7684210526622, 100000), (3139.578947368433, 100000), (2935.4684210526652, 100000), (2872.3736842105645, 100000), (3002.1157894737134, 100000), (2994.110526315821, 100000), (2945.4631578947633, 100000), (3090.221052631607, 100000), (3004.389473684234, 100000), (3033.1894736842264, 100000), (2888.5736842105507, 100000), (3012.6315789474074, 100000), (3068.9526315789763, 100000), (3302.3368421053137, 100000), (3073.073684210562, 100000), (3006.28421052633, 100000), (3266.478947368447, 100000), (2997.5210526316164, 100000), (3090.600000000025, 100000), (3006.7578947368725, 100000), (2963.084210526333, 100000), (2943.8526315789886, 100000), (2961.2368421052947, 100000), (3299.352631578963, 100000), (3092.6368421053153, 100000), (3005.100000000031, 100000), (3092.1631578947718, 100000), (3101.4947368421244, 100000), (3143.5105263158152, 100000), (3205.0894736842533, 250000), (3234.4105263158135, 250000), (3209.9210526316233, 250000), (3157.7684210526604, 250000), (2967.7736842105496, 250000), (3114.805263157892, 250000), (3049.9105263158276, 250000), (2967.7263157894745, 250000), (3216.1263157895223, 250000), (3077.194736842128, 250000), (3125.700000000034, 250000), (2960.052631578982, 250000), (2948.7315789473832, 250000), (2958.963157894752, 250000), (3109.594736842137, 250000), (2922.252631578978, 250000), (2762.6210526316045, 250000), (3006.615789473727, 250000), (3029.115789473735, 250000), (2964.4105263158203, 250000), (3034.610526315813, 250000), (3137.778947368454, 250000), (3117.7894736842545, 250000), (3180.9315789473676, 250000), (3241.847368421068, 250000), (3070.9894736842375, 250000), (2994.347368421068, 250000), (3171.1736842105634, 250000), (3042.0000000000177, 250000), (3137.5421052631827, 250000), (3087.5210526316155, 250000), (2838.8842105263366, 250000), (2848.1210526316104, 250000), (3169.184210526343, 250000), (3268.5157894737167, 250000), (2961.568421052647, 250000), (2991.0789473684326, 250000), (2818.894736842137, 250000), (3152.463157894744, 250000), (3198.2684210526495, 250000), (3211.3421052631898, 250000), (2806.578947368446, 250000), (3009.221052631589, 250000), (2834.005263157912, 250000), (3203.242105263177, 250000), (3148.578947368449, 250000), (3197.842105263183, 250000), (3017.1315789473756, 250000), (3156.5368421052854, 250000), (3024.947368421058, 250000), (3117.600000000045, 250000), (3288.3157894736955, 250000), (3127.5473684210656, 250000), (3000.600000000014, 250000), (3278.7000000000407, 250000), (3208.2157894737193, 250000), (3147.963157894777, 250000), (3301.389473684236, 250000), (3121.9105263158326, 250000), (2925.7578947368756, 250000), (3140.952631578962, 250000), (2923.200000000025, 250000), (3218.2105263158, 250000), (3039.963157894745, 250000), (3213.8526315789854, 250000), (3059.289473684248, 250000), (2951.1947368421193, 250000), (3125.1789473684516, 250000), (3318.157894736888, 250000), (2996.9052631579343, 250000), (3307.6421052631895, 250000), (2921.447368421073, 250000), (2974.310526315829, 250000), (2932.8157894737237, 250000), (3212.905263157925, 250000), (3181.6894736842355, 250000), (2885.3526315789686, 250000), (3223.2789473684566, 250000), (3084.7736842105555, 250000), (3033.0473684210783, 250000), (3367.752631578976, 250000), (3133.8000000000275, 250000), (3139.768421052645, 250000), (3140.857894736885, 250000), (2823.442105263191, 250000), (3098.5105263158066, 250000), (3239.1473684210996, 250000), (3168.473684210563, 250000), (3214.4210526316015, 250000), (3080.5578947368676, 250000)]

In [24]:
regrets = [item[0] for item in A]

for i, param in enumerate(params):
    if param[-1] == 1:
        print(regrets[i])

3082.1684210526664
3070.5631578947646
2991.2684210526522
2972.8894736842267
3135.6947368421165
3039.678947368444
3143.415789473717
3104.1000000000295
3068.621052631611
3130.9578947368736
3096.0473684210624
3024.331578947394
3159.9473684210834
3116.036842105296
3309.631578947378
3105.0000000000286
3114.1894736842482
3050.857894736878
3361.9263157894857
2949.8210526315993
3014.9052631579116
2935.4684210526652
2994.110526315821
3004.389473684234
3012.6315789474074
3073.073684210562
2997.5210526316164
2963.084210526333
3299.352631578963
3092.1631578947718
3205.0894736842533
3157.7684210526604
3049.9105263158276
3077.194736842128
2948.7315789473832
2922.252631578978
3029.115789473735
3137.778947368454
3241.847368421068
3171.1736842105634
3087.5210526316155
3169.184210526343
2991.0789473684326
3198.2684210526495
3009.221052631589
3148.578947368449
3156.5368421052854
3288.3157894736955
3278.7000000000407
3301.389473684236
3140.952631578962
3039.963157894745
2951.1947368421193
2996.90526315793

In [23]:
params = [(False, 1, 'MP', 0, 1), (False, 1, 'MP', 0, 3), (False, 1, 'MP', 0, 5), (False, 1, 'MP', 1, 1), (False, 1, 'MP', 1, 3), (False, 1, 'MP', 1, 5), (False, 1, 'MP', 2, 1), (False, 1, 'MP', 2, 3), (False, 1, 'MP', 2, 5), (False, 1, 'MP', 3, 1), (False, 1, 'MP', 3, 3), (False, 1, 'MP', 3, 5), (False, 1, 'MP', 4, 1), (False, 1, 'MP', 4, 3), (False, 1, 'MP', 4, 5), (False, 1, 'MP', 5, 1), (False, 1, 'MP', 5, 3), (False, 1, 'MP', 5, 5), (False, 1, 'MP', 6, 1), (False, 1, 'MP', 6, 3), (False, 1, 'MP', 6, 5), (False, 1, 'MP', 7, 1), (False, 1, 'MP', 7, 3), (False, 1, 'MP', 7, 5), (False, 1, 'MP', 8, 1), (False, 1, 'MP', 8, 3), (False, 1, 'MP', 8, 5), (False, 1, 'MP', 9, 1), (False, 1, 'MP', 9, 3), (False, 1, 'MP', 9, 5), (False, 1, 'Greedy-MP', 0, 1), (False, 1, 'Greedy-MP', 0, 3), (False, 1, 'Greedy-MP', 0, 5), (False, 1, 'Greedy-MP', 1, 1), (False, 1, 'Greedy-MP', 1, 3), (False, 1, 'Greedy-MP', 1, 5), (False, 1, 'Greedy-MP', 2, 1), (False, 1, 'Greedy-MP', 2, 3), (False, 1, 'Greedy-MP', 2, 5), (False, 1, 'Greedy-MP', 3, 1), (False, 1, 'Greedy-MP', 3, 3), (False, 1, 'Greedy-MP', 3, 5), (False, 1, 'Greedy-MP', 4, 1), (False, 1, 'Greedy-MP', 4, 3), (False, 1, 'Greedy-MP', 4, 5), (False, 1, 'Greedy-MP', 5, 1), (False, 1, 'Greedy-MP', 5, 3), (False, 1, 'Greedy-MP', 5, 5), (False, 1, 'Greedy-MP', 6, 1), (False, 1, 'Greedy-MP', 6, 3), (False, 1, 'Greedy-MP', 6, 5), (False, 1, 'Greedy-MP', 7, 1), (False, 1, 'Greedy-MP', 7, 3), (False, 1, 'Greedy-MP', 7, 5), (False, 1, 'Greedy-MP', 8, 1), (False, 1, 'Greedy-MP', 8, 3), (False, 1, 'Greedy-MP', 8, 5), (False, 1, 'Greedy-MP', 9, 1), (False, 1, 'Greedy-MP', 9, 3), (False, 1, 'Greedy-MP', 9, 5), (False, 1, 'HMP', 0, 1), (False, 1, 'HMP', 0, 3), (False, 1, 'HMP', 0, 5), (False, 1, 'HMP', 1, 1), (False, 1, 'HMP', 1, 3), (False, 1, 'HMP', 1, 5), (False, 1, 'HMP', 2, 1), (False, 1, 'HMP', 2, 3), (False, 1, 'HMP', 2, 5), (False, 1, 'HMP', 3, 1), (False, 1, 'HMP', 3, 3), (False, 1, 'HMP', 3, 5), (False, 1, 'HMP', 4, 1), (False, 1, 'HMP', 4, 3), (False, 1, 'HMP', 4, 5), (False, 1, 'HMP', 5, 1), (False, 1, 'HMP', 5, 3), (False, 1, 'HMP', 5, 5), (False, 1, 'HMP', 6, 1), (False, 1, 'HMP', 6, 3), (False, 1, 'HMP', 6, 5), (False, 1, 'HMP', 7, 1), (False, 1, 'HMP', 7, 3), (False, 1, 'HMP', 7, 5), (False, 1, 'HMP', 8, 1), (False, 1, 'HMP', 8, 3), (False, 1, 'HMP', 8, 5), (False, 1, 'HMP', 9, 1), (False, 1, 'HMP', 9, 3), (False, 1, 'HMP', 9, 5), (False, None, 'MP', 0, 1), (False, None, 'MP', 0, 3), (False, None, 'MP', 0, 5), (False, None, 'MP', 1, 1), (False, None, 'MP', 1, 3), (False, None, 'MP', 1, 5), (False, None, 'MP', 2, 1), (False, None, 'MP', 2, 3), (False, None, 'MP', 2, 5), (False, None, 'MP', 3, 1), (False, None, 'MP', 3, 3), (False, None, 'MP', 3, 5), (False, None, 'MP', 4, 1), (False, None, 'MP', 4, 3), (False, None, 'MP', 4, 5), (False, None, 'MP', 5, 1), (False, None, 'MP', 5, 3), (False, None, 'MP', 5, 5), (False, None, 'MP', 6, 1), (False, None, 'MP', 6, 3), (False, None, 'MP', 6, 5), (False, None, 'MP', 7, 1), (False, None, 'MP', 7, 3), (False, None, 'MP', 7, 5), (False, None, 'MP', 8, 1), (False, None, 'MP', 8, 3), (False, None, 'MP', 8, 5), (False, None, 'MP', 9, 1), (False, None, 'MP', 9, 3), (False, None, 'MP', 9, 5), (False, None, 'Greedy-MP', 0, 1), (False, None, 'Greedy-MP', 0, 3), (False, None, 'Greedy-MP', 0, 5), (False, None, 'Greedy-MP', 1, 1), (False, None, 'Greedy-MP', 1, 3), (False, None, 'Greedy-MP', 1, 5), (False, None, 'Greedy-MP', 2, 1), (False, None, 'Greedy-MP', 2, 3), (False, None, 'Greedy-MP', 2, 5), (False, None, 'Greedy-MP', 3, 1), (False, None, 'Greedy-MP', 3, 3), (False, None, 'Greedy-MP', 3, 5), (False, None, 'Greedy-MP', 4, 1), (False, None, 'Greedy-MP', 4, 3), (False, None, 'Greedy-MP', 4, 5), (False, None, 'Greedy-MP', 5, 1), (False, None, 'Greedy-MP', 5, 3), (False, None, 'Greedy-MP', 5, 5), (False, None, 'Greedy-MP', 6, 1), (False, None, 'Greedy-MP', 6, 3), (False, None, 'Greedy-MP', 6, 5), (False, None, 'Greedy-MP', 7, 1), (False, None, 'Greedy-MP', 7, 3), (False, None, 'Greedy-MP', 7, 5), (False, None, 'Greedy-MP', 8, 1), (False, None, 'Greedy-MP', 8, 3), (False, None, 'Greedy-MP', 8, 5), (False, None, 'Greedy-MP', 9, 1), (False, None, 'Greedy-MP', 9, 3), (False, None, 'Greedy-MP', 9, 5), (False, None, 'HMP', 0, 1), (False, None, 'HMP', 0, 3), (False, None, 'HMP', 0, 5), (False, None, 'HMP', 1, 1), (False, None, 'HMP', 1, 3), (False, None, 'HMP', 1, 5), (False, None, 'HMP', 2, 1), (False, None, 'HMP', 2, 3), (False, None, 'HMP', 2, 5), (False, None, 'HMP', 3, 1), (False, None, 'HMP', 3, 3), (False, None, 'HMP', 3, 5), (False, None, 'HMP', 4, 1), (False, None, 'HMP', 4, 3), (False, None, 'HMP', 4, 5), (False, None, 'HMP', 5, 1), (False, None, 'HMP', 5, 3), (False, None, 'HMP', 5, 5), (False, None, 'HMP', 6, 1), (False, None, 'HMP', 6, 3), (False, None, 'HMP', 6, 5), (False, None, 'HMP', 7, 1), (False, None, 'HMP', 7, 3), (False, None, 'HMP', 7, 5), (False, None, 'HMP', 8, 1), (False, None, 'HMP', 8, 3), (False, None, 'HMP', 8, 5), (False, None, 'HMP', 9, 1), (False, None, 'HMP', 9, 3), (False, None, 'HMP', 9, 5)]